[pokemon]
"야돈" = ["야돈", "Slowpoke", "ヤドン"]
"피카츄" = ["피카츄", "Pikachu", "ピカチュウ"]
"이브이" = ["이브이", "Eevee", "イーブイ"]
"메타몽" = ["메타몽", "Ditto", "メタモン"]
"잠만보" = ["잠만보", "Snorlax", "カビゴン"]
"리자몽" = ["리자몽", "Charizard", "リザードン"]
"뮤츠" = ["뮤츠", "Mewtwo", "ミュウツー"]
"꼬부기" = ["꼬부기", "Squirtle", "ゼニガメ"]
"파이리" = ["파이리", "Charmander", "ヒトカゲ"]
"이상해씨" = ["이상해씨", "Bulbasaur", "フシギダネ"]
"코라이돈" = ["코라이돈", "Koraidon", "コライドン"]
"미라이돈" = ["미라이돈", "Miraidon", "ミライドン"]
"레쿠쟈" = ["레쿠쟈", "Rayquaza", "レックウザ"]
